name: 'action-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get commit sha
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Modify name of the package.json
        uses: ./
        with:
          key: 'name'
          value: '@maxgfr/example-${{ env.GITHUB_SHA }}'
          path: example/package.json
          commit: true
      - name: Modify name of the package.json locally
        uses: ./
        with:
          key: 'name'
          value: 'yo'
          path: ./example/package.json